### ISSUE TITLE
Google Lens Enabler compability

### ISSUE THREAD

**Issue by RubenKelevra** [Magisk-Modules-Repo/op5tcamlibfix#1]
Since the OnePlus 5T is not supported by Google Lens, I have to use the Google Lens enabler modul (which works fine). But then the video camera in the stock firmware does not record anything. The files get created at an appropriate size but can be played neither on a computer nor the phone.

I hope you can fix this too - it's probably just a copy protection (the phone is detected as a Pixel XL after the Google Lens Enabler) for the stock camera app since with other apps it's working fine.

**Comment by nipunnarang** [comment]
> Since the OnePlus 5T is not supported by Google Lens, I have to use the Google Lens enabler modul (which works fine). But then the video camera in the stock firmware does not record anything. The files get created at an appropriate size but can be played neither on a computer nor the phone.
> 
> I hope you can fix this too - it's probably just a copy protection (the phone is detected as a Pixel XL after the Google Lens Enabler) for the stock camera app since with other apps it's working fine.

Hi! That module that you've referenced in your comment was made by me too, and it only enables Google Lens in Google Photos, not in Google Camera/stock OxygenOS Camera. I don't think there is a way to enable Google Lens in Google Camera/stock OxygenOS Camera at the moment. Even if someone finds out a way to do that, there is a high chance that it won't require edits to the camera HAL but would require apk modification of the app in which you want Google Lens to be accessible, hence making it out-of-scope of this module. Thanks!

**Comment by RubenKelevra** [comment]
Hey, @nipunnarang thank you for your fast feedback. I dug a bit into my enabled modules and tried to disable one by one.

It looks like Google Daydream enabler is the cause of this issue, not your Lens enabler one.

Sorry for bothering you again, but do you think it's possible to fix this incompatibility? :/

**Comment by nipunnarang** [comment]
> Hey, @nipunnarang thank you for your fast feedback. I dug a bit into my enabled modules and tried to disable one by one.
> 
> It looks like Google Daydream enabler is the cause of this issue, not your Lens enabler one.
> 
> Sorry for bothering you again, but do you think it's possible to fix this incompatibility? :/

No problem at all! Also, not sure if the incompatibility can be fixed. Like I said before, I doubt the camera HAL has to edited for that, and apk modification is something I'm not very experienced with, so.
